title: binhsonnguyen
email: binhson.nguyen@icloud.com
description:

baseurl: ""
url: "http://binhsonnguyen.com"
github_username: binhsonnguyen
emojilock_id: ğŸ’¥ğŸš¿ğŸ¬ğŸ´ğŸ¸ğŸ‘ğŸŒğŸ’°ğŸŒğŸâŒ›ï¸âš½ï¸âš“ï¸ğŸ™ğŸ’§ğŸ’˜ğŸ‘”ğŸ’«ğŸ”‰ğŸºğŸŒ¹ğŸ’‰ğŸ‘«ğŸ‘½ğŸ’¢ğŸğŸƒğŸš¦ğŸš«ğŸ•ğŸ”­ğŸ…°

# Build settings
markdown: kramdown
theme: minima

# Liquid
error_mode: strict

disqus:
  shortname: binhsonnguyen
