title: binhson.nguyen's awesome blog (=^._.^=) ( à¹‘à¥”ËƒÌ¶â—¡â€ŠË‚Ì¶à¹‘à¥“)
email: binhson.nguyen@icloud.com
description:
  binhson.nguyen's awesome blog (=^._.^=) ( à¹‘à¥”ËƒÌ¶â—¡â€ŠË‚Ì¶à¹‘à¥“)
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://binhsonnguyen.com" # the base hostname & protocol for your site
github_username: binhsonnguyen
emojilock_id: ğŸ’¥ğŸš¿ğŸ¬ğŸ´ğŸ¸ğŸ‘ğŸŒğŸ’°ğŸŒğŸâŒ›ï¸âš½ï¸âš“ï¸ğŸ™ğŸ’§ğŸ’˜ğŸ‘”ğŸ’«ğŸ”‰ğŸºğŸŒ¹ğŸ’‰ğŸ‘«ğŸ‘½ğŸ’¢ğŸğŸƒğŸš¦ğŸš«ğŸ•ğŸ”­ğŸ…°

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Liquid
error_mode: strict
